import { Link } from "react-router";
import { PageTransition } from "../../components/ui/PageTransition";
import { PipelineHero } from "../../features/product/PipelineHero";
import { SourceExplorer } from "../../features/product/SourceExplorer";
import { CompilerStory } from "../../features/product/CompilerStory";
import { Visual } from "../../features/product/Visual";
import { PlatformOutputs } from "../../features/product/PlatformOutputs";
import { RealApps } from "../../features/product/RealApps";
import { DeferredEvidence } from "../../features/product/DeferredEvidence";
import { CliWorkflow } from "../../features/product/CliWorkflow";
import { RepositoryGraph } from "../../features/product/RepositoryGraph";

export function Component(): React.JSX.Element {
  return <PageTransition className="product-page">
    <section className="product-hero product-wide"><div className="product-hero__copy"><p className="product-kicker">Compiler-powered native client runtime</p><h1>One client definition.<br /><span>Two native platforms.</span></h1><p>Define shared models, requests, and repositories in <code>.cra</code>. Crossa validates them in C++ and generates an Android AAR and iOS XCFramework backed by one native runtime.</p><p className="hero-ownership"><span>C++ owns</span> networking · scheduling · typed decoding</p><div className="product-actions"><Link className="button button--primary" to="/docs/getting-started">Get started ↗</Link><a className="button button--secondary" href="#product">How Crossa works ↓</a></div><p className="artifact-signature">.cra → typed IR → native runtime → Kotlin + Swift</p></div><PipelineHero /></section>
    <section className="product-section product-wide problem-section" id="product"><div className="product-heading"><span className="chapter">01 / The reason</span><h2>Mobile networking<br />shouldn’t be built twice.</h2><p>Two apps often mean two implementations of the same requests, response models and error rules. Crossa moves that shared client behavior into one definition and one native execution path.</p></div><Visual name="duplication" /><div className="problem-summary"><span>Keep your Kotlin and Swift UI.</span><strong>Share the behavior underneath.</strong></div></section>
    <section className="product-section product-wide source-section"><div><span className="chapter">02 / The input</span><h2>This is what<br />you actually write.</h2><p>Four real files from the Android example. A model defines the result, a request defines the operation, a repository links it, and configuration sets the runtime bounds.</p><Link className="product-link" to="/examples">Explore the language in context ↗</Link></div><SourceExplorer /></section>
    <section className="product-section product-wide"><div className="product-heading"><span className="chapter">03 / The transformation</span><h2>From source to semantics.<br />Then to your app.</h2><p>One canonical frontend. Follow a request through the compiler and into native execution.</p></div><CompilerStory /></section>
    <section className="product-section runtime-section" id="native-runtime"><div className="product-wide"><div className="product-heading"><span className="chapter">04 / The engine</span><h2>One runtime.<br /><span>Clear ownership.</span></h2><p>C++ owns transport, bounded response buffers, typed decoding, model storage and cancellation. Kotlin and Swift expose that behavior through thin native bridges.</p></div><Visual name="runtime" /><div className="runtime-footnote"><strong>The work stays native.</strong><p>The current decoder builds typed scalar, model and list values directly from a bounded response buffer. Platform result views retain native storage; they don’t implement another response parser.</p><Link className="product-link" to="/docs/runtime/architecture">Read the ownership contract ↗</Link></div></div></section>
    <section className="product-section product-wide" id="platforms"><div className="product-heading"><span className="chapter">05 / The outputs</span><h2>Real artifacts.<br />Familiar app APIs.</h2><p>The same request definition becomes a project-specific SDK for each platform, backed by Crossa’s C++ runtime.</p></div><PlatformOutputs /></section>
    <section className="product-section apps-section"><div className="product-wide"><div className="product-heading"><span className="chapter">06 / In an application</span><h2>Meet the consumers.</h2><p>These example apps call JSONPlaceholder through generated Crossa APIs and compare their retained observations with platform networking clients.</p></div><RealApps /><p className="capture-note">Score-only device previews show the same library comparisons used by the normalized benchmark data below.</p></div></section>
    <section className="product-section product-wide"><div className="product-heading"><span className="chapter">07 / Measured evidence</span><h2>Look at the run.<br />Not a speed claim.</h2><p>Release artifacts, eight measured rounds per implementation, and a remote endpoint. Explore both platforms and both startup modes.</p></div><DeferredEvidence /><Link className="product-link" to="/benchmarks">Open the full report & raw samples ↗</Link></section>
    <section className="product-section product-wide workflow-section" id="cli"><div><span className="chapter">08 / Your workflow</span><h2>Check.<br />Generate.<br />Integrate.</h2><p>Use explicit commands to inspect prerequisites, validate source and produce a platform project. Android adds Gradle assembly; iOS generation archives the framework.</p><Link className="product-link" to="/docs/cli">CLI reference ↗</Link></div><CliWorkflow /></section>
    <section className="product-section product-wide"><div className="product-heading"><span className="chapter">09 / The ecosystem</span><h2>One core.<br />Two working examples.</h2></div><RepositoryGraph /></section>
    <section className="product-finish product-wide"><code>.cra → Crossa → your app</code><h2>Start with one .cra file.</h2><div className="product-actions"><Link className="button button--primary" to="/docs/getting-started">Read getting started ↗</Link><Link className="product-link" to="/examples">Explore examples →</Link></div></section>
  </PageTransition>;
}
