import { ArrowRight, ArrowUpRight, Boxes, Code2, FolderTree, Github, Smartphone } from "lucide-react";
import { Link, useParams } from "react-router";
import { PageTransition } from "../../components/ui/PageTransition";

interface Repository { readonly id: string; readonly title: string; readonly eyebrow: string; readonly description: string; readonly responsibility: readonly string[]; readonly directories: readonly string[]; readonly commands: readonly string[]; readonly docs: readonly [string, string][]; readonly remote: string; }
const repositories: readonly Repository[] = [
  { id: "crossa", title: "Crossa Core", eyebrow: "Compiler + native runtime", description: "The C++20 compiler frontend, typed IR, native runtime, networking path, stable ABI, generators, packaging, and CLI.", responsibility: [".cra loader, lexer, parser, and project linker", "Semantic analysis and platform-neutral typed IR", "Native request execution, decoding, scheduler, ownership", "Android/iOS generators, artifact creation, CLI"], directories: ["src/compiler", "src/runtime", "src/network", "src/platform", "docs/"], commands: ["cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug", "cmake --build build", "./build/crossa doctor"], docs: [["Language foundation", "/docs/language"], ["Runtime architecture", "/docs/runtime/architecture"], ["CLI", "/docs/cli"]], remote: "https://github.com/crossa-script/Crossa" },
  { id: "android-example", title: "Android Example", eyebrow: "Release AAR consumer", description: "An Android consumer of a generated Crossa Release AAR, with Crossa, Retrofit+OkHttp, and Ktor observation harnesses against JSONPlaceholder.", responsibility: ["Release AAR integration", "Generated Kotlin API usage", "Crossa / Retrofit / Ktor benchmark harness", "Artifact manifest verification"], directories: ["app/src/main", "app/libs", "benchmark-results/", "scripts/"], commands: ["./scripts/generate-build.sh", "./gradlew verifyDemo", "./gradlew :app:assembleRelease"], docs: [["Android getting started", "/docs/android/getting-started"], ["AAR generation", "/docs/android/aar"], ["Benchmark evidence", "/docs/benchmarks"]], remote: "https://github.com/crossa-script/android-example" },
  { id: "ios-example", title: "iOS Example", eyebrow: "Release XCFramework consumer", description: "A standalone SwiftUI app consuming a generated Crossa Release XCFramework, with Crossa and Alamofire benchmark observation paths.", responsibility: ["Release XCFramework integration", "SwiftUI usage", "Crossa / Alamofire benchmark harness", "Generated framework manifest and checksum workflow"], directories: ["CrossaIOSExample/", "CrossaPackage/", "crossa/", "benchmark-results/"], commands: ["crossa generate-build ios ./ios-example/crossa --output ./build/crossa-ios", "./scripts/install-crossa-framework.sh ../build/crossa-ios/release/Crossa.xcframework"], docs: [["iOS getting started", "/docs/ios/getting-started"], ["XCFramework generation", "/docs/ios/xcframework"], ["Benchmark evidence", "/docs/benchmarks"]], remote: "https://github.com/crossa-script/ios-example" }
];

function RepositoryDetail({ repository }: { readonly repository: Repository }): React.JSX.Element { return <PageTransition><div className="repository-detail shell"><Link className="back-link" to="/repositories">← All repositories</Link><div className="repository-detail__hero"><p className="eyebrow">{repository.eyebrow}</p><h1>{repository.title}</h1><p>{repository.description}</p><a className="button button--primary" href={repository.remote} target="_blank" rel="noreferrer"><Github size={17} /> Open on GitHub <ArrowUpRight size={15} /></a></div><div className="repository-detail__grid"><section><h2>Responsibility</h2><ul>{repository.responsibility.map((item) => <li key={item}>{item}</li>)}</ul></section><section><h2>Main directories</h2><div className="directory-list">{repository.directories.map((item) => <code key={item}><FolderTree size={15} />{item}</code>)}</div></section><section><h2>Useful commands</h2>{repository.commands.map((item) => <pre key={item}>{item}</pre>)}</section><section><h2>Related docs</h2>{repository.docs.map(([label, href]) => <Link key={href} to={href}>{label}<ArrowRight size={16} /></Link>)}</section></div></div></PageTransition>; }

export function Component(): React.JSX.Element {
  const { repository: repositoryId } = useParams();
  const repository = repositories.find((entry) => entry.id === repositoryId);
  if (repository) return <RepositoryDetail repository={repository} />;
  return <PageTransition className="repositories-page"><section className="shell page-intro"><p className="eyebrow">Crossa ecosystem</p><h1>One core path, verified by platform consumers.</h1><p>Crossa Core owns the compiler and runtime. Android and iOS example repositories consume generated Release artifacts and retain the benchmark snapshots shown in this site.</p></section><section className="shell repository-cards">{repositories.map((entry, index) => <Link className="repository-card" key={entry.id} to={`/repositories/${entry.id}`}><span className={`repository-icon repository-icon--${index}`} >{index === 0 ? <Boxes size={22} /> : index === 1 ? <Smartphone size={22} /> : <Code2 size={22} />}</span><p>{entry.eyebrow}</p><h2>{entry.title}</h2><span>{entry.description}</span><b>Explore repository <ArrowRight size={16} /></b></Link>)}</section></PageTransition>;
}
