import { useState } from "react";
import { Link, useParams } from "react-router";
import { PageTransition } from "../../components/ui/PageTransition";
import { repositories } from "../../content/product/story";
import { RepositoryGraph } from "../../features/product/RepositoryGraph";
import { Visual } from "../../features/product/Visual";
import { PlatformOutputs } from "../../features/product/PlatformOutputs";
import { RealApps } from "../../features/product/RealApps";
import { BenchmarkExplorer } from "../../features/benchmarks/BenchmarkExplorer";
import { Component as NotFound } from "../not-found/route";

function SourceTree({ repository }: { readonly repository: typeof repositories[number] }): React.JSX.Element {
  const [selected, setSelected] = useState(0);
  const folder = repository.folders[selected]!;
  return <div className="source-tree"><nav aria-label="Repository folders">{repository.folders.map(([path], index) => <button type="button" key={path} aria-pressed={selected === index} onClick={() => setSelected(index)}><span>↳</span> {path}</button>)}</nav><div aria-live="polite"><p>Source map</p><h3>{folder[0]}</h3><p>{folder[1]}</p><a className="product-link" href={`https://github.com/crossa-script/${repository.id === "crossa" ? "Crossa" : repository.id}/tree/main/${folder[0]}`} target="_blank" rel="noreferrer">Browse folder on GitHub ↗</a></div></div>;
}

export function Component(): React.JSX.Element {
  const { repository: id } = useParams();
  const repository = repositories.find((entry) => entry.id === id);
  if (id && !repository) return <NotFound />;
  if (!repository) return <PageTransition className="product-page"><header className="product-intro product-wide"><p className="chapter">The Crossa ecosystem</p><h1>Follow the source.<br /><span>Through to the app.</span></h1><p>Crossa Core defines the compiler and native execution contract. The Android and iOS examples consume generated Release artifacts, exercise their platform APIs, and retain the evidence used by this website.</p></header><section className="product-wide product-section"><RepositoryGraph /></section><section className="product-wide product-section ecosystem-responsibilities"><div><span className="chapter">What lives where</span><h2>Three repositories.<br />One delivery chain.</h2></div><div className="responsibility-ledger"><article><span>01</span><div><h3>Crossa Core owns semantics.</h3><p>Source loading, parsing, type validation, typed IR, the native scheduler and network runtime, Android and iOS generators, packaging, and the CLI all live in the core repository.</p></div></article><article><span>02</span><div><h3>Android proves the AAR path.</h3><p>The Compose consumer integrates generated Kotlin APIs and JNI-backed native values. Its harness compares the Release AAR with Retrofit + OkHttp and Ktor under the same request configuration.</p></div></article><article><span>03</span><div><h3>iOS proves the XCFramework path.</h3><p>The SwiftUI consumer integrates a project-specific XCFramework through Swift Package Manager. Swift calls the generated API over Crossa’s stable C ABI and retains matching benchmark provenance.</p></div></article></div></section><section className="product-wide product-finish"><h2>Read it. Build it. Trace it.</h2><p>Start in the core when you need compiler or runtime behavior. Open a platform example when you need integration, lifecycle, artifact, or benchmark evidence.</p><Link className="product-link" to="/docs/getting-started">Start with the toolchain ↗</Link></section></PageTransition>;
  const platform = repository.id === "android-example" ? "android" : repository.id === "ios-example" ? "ios" : undefined;
  return <PageTransition className="product-page"><header className="product-intro product-wide"><Link className="product-link" to="/repositories">← Ecosystem</Link><p className="chapter">{repository.role}</p><h1>{repository.name}</h1><p>{repository.description}</p><a className="button button--secondary" href={`https://github.com/crossa-script/${repository.id === "crossa" ? "Crossa" : repository.id}`} target="_blank" rel="noreferrer">Open repository ↗</a></header><section className="product-wide repository-overview">{platform ? <><RealApps platform={platform} /><div><h2>The integration path.</h2><p className="integration-path">{repository.role}</p><Visual name={platform} /></div></> : <><div><h2>Source becomes<br />native behavior.</h2><p>The frontend links and validates the project before generators create platform surfaces. The runtime owns operation execution; the bindings own the boundary.</p></div><Visual name="pipeline" /></>}</section>{!platform && <section className="product-section product-wide core-ownership"><div><span className="chapter">Responsibility boundary</span><h2>What the core owns.</h2></div><div className="responsibility-ledger"><article><span>01</span><div><h3>Compiler frontend</h3><p>Loads the project graph, parses every <code>.cra</code> file, resolves imports, checks types and execution policies, then lowers the validated program into platform-neutral typed IR.</p></div></article><article><span>02</span><div><h3>Native execution</h3><p>Coordinates bounded scheduling, request encoding, HTTP transport, response buffering, schema-aware decoding, native model storage, cancellation, errors, and shutdown.</p></div></article><article><span>03</span><div><h3>Platform boundaries</h3><p>Generates Kotlin and Swift APIs over concentrated JNI and stable C ABI layers. These surfaces expose native work without becoming independent networking implementations.</p></div></article><article><span>04</span><div><h3>Artifact delivery</h3><p>Produces project-specific Android and iOS build projects, records source and CLI identity in manifests, and packages the runtime with the operations and models the client declared.</p></div></article></div></section>}<section className="product-section product-wide"><h2>Find the implementation.</h2><SourceTree key={repository.id} repository={repository} /></section>{platform ? <><section className="product-section product-wide"><PlatformOutputs platform={platform} /></section><section className="product-section product-wide"><h2>Retained Release evidence.</h2><BenchmarkExplorer key={platform} initialPlatform={platform} /><Link className="product-link" to="/benchmarks">Inspect raw samples and provenance ↗</Link></section></> : <section className="product-section product-wide"><h2>Inside the native boundary.</h2><Visual name="runtime" /><Link className="product-link" to="/docs/runtime/architecture">Read the runtime contract ↗</Link></section>}</PageTransition>;
}
