export type DocumentationSection = "start" | "language" | "runtime" | "platform" | "cli" | "reference";

export interface DocumentationDefinition {
  readonly slug: string;
  readonly title: string;
  readonly description: string;
  readonly section: DocumentationSection;
  readonly order: number;
  readonly sourceRepository: "crossa" | "android-example" | "ios-example";
  readonly sourcePaths: readonly string[];
  readonly verifiedCommit: string;
  readonly content: string;
}

const commit = "8c362e1";
const code = "```cra\nmodel Post(\n    id: Int,\n    title: String\n)\n\n@AsyncAfter\nfun getPosts(): List<Post> {\n    re CrossaRequest {\n        url: \"https://jsonplaceholder.typicode.com/posts\",\n        method: GET\n    }\n}\n```";

function doc(
  slug: string,
  title: string,
  description: string,
  section: DocumentationSection,
  order: number,
  sourcePaths: readonly string[],
  content: string,
  sourceRepository: DocumentationDefinition["sourceRepository"] = "crossa",
): DocumentationDefinition {
  return { slug, title, description, section, order, sourceRepository, sourcePaths, verifiedCommit: commit, content };
}

export const documentationCatalog = [
  doc("/docs", "Documentation", "A verified map of the Crossa V0 workflow.", "start", 0, ["README.md"], `# Crossa documentation\n\nCrossa compiles compact \`.cra\` source through a shared C++ frontend and runtime, then exposes Android and iOS integration surfaces. This portal is curated against Crossa commit \`${commit}\`.\n\n> Crossa is in its foundation phase. Streaming delivery to platform APIs and generated direct decoders are still in progress.\n\n## Start here\n\n1. Install the CLI.\n2. Run \`crossa doctor\`.\n3. Write a small \`.cra\` source file.\n4. Generate an Android project or iOS XCFramework when your project is ready.`),
  doc("/docs/getting-started", "Getting started", "From install to a generated native artifact.", "start", 10, ["README.md", "docs/development/cli.md"], `# Getting started\n\nCrossa is a compiler and native runtime for \`.cra\` sources. The C++ frontend parses and validates source once; platform bindings consume the resulting native program.\n\n## 1. Install and inspect\n\n\`crossa doctor\` checks the local Crossa installation and Android/iOS prerequisites without installing or changing system settings.\n\n\`\`\`bash\ncrossa --version\ncrossa doctor\n\`\`\`\n\n## 2. Define a request\n\n${code}\n\n## 3. Build the platform artifact\n\n\`crossa generate-build android ./project --output ./build/crossa-aar\` writes an Android Gradle library project. \`crossa generate-build ios ./project --output ./build/crossa-ios\` writes and archives Debug and Release XCFrameworks.`),
  doc("/docs/installation", "Installation", "Install a released Crossa CLI and verify the toolchain.", "start", 20, ["README.md"], `# Installation\n\nRelease installers download a compiled Crossa binary from GitHub Releases and verify it with \`SHA256SUMS\`. They do not require \`sudo\`.\n\n\`\`\`bash\ncurl -fsSL https://raw.githubusercontent.com/crossa-script/Crossa/main/scripts/install/install.sh | bash\ncrossa --version\ncrossa doctor\n\`\`\`\n\nWindows has a PowerShell installer; see the core repository README for the current command. The installer prints a PATH instruction if needed.`),
  doc("/docs/quick-start", "Quick start", "Run a pure function, then validate it without execution.", "start", 30, ["README.md", "docs/language/language-foundation.md"], `# Quick start\n\nCreate \`hello.cra\` and run it through the native runtime.\n\n\`\`\`cra\nfun add(a: Int, b: Int): Int {\n    re a + b\n}\n\nprint(add(1, 2))\n\`\`\`\n\n\`\`\`bash\ncrossa run hello.cra\ncrossa check hello.cra\n\`\`\`\n\n\`check\` validates loading, imports, syntax, semantics, and typed IR lowering without executing reachable calls.`),
  doc("/docs/language", "Crossa language", "The deliberately small, typed .cra language surface.", "language", 0, ["docs/language/language-foundation.md"], `# The .cra language\n\nCrossa language is intentionally small: it describes functions, typed models, configuration, execution policy, and native requests. It is not a general-purpose language.\n\n## Current foundation\n\nThe V0 surface includes \`fun\`, \`re\`, \`var\`, \`model\`, \`config\`, \`import\`, \`if\`, \`else\`, \`List<T>\`, \`@Sync\`, \`@Async\`, \`@AsyncAfter\`, interpolation, and \`CrossaRequest\`.\n\n${code}`),
  doc("/docs/language/source-files", "Source files", "File identity and project-level source organization.", "language", 10, ["docs/language/language-foundation.md"], `# Source files\n\nEach \`.cra\` file is one Crossa source unit. For files that create a generated platform container, the filename stem becomes its deterministic generated identity. Renaming such a file can change a generated API.\n\n\`config.cra\` is reserved for project/runtime configuration and does not become an ordinary generated class.`),
  doc("/docs/language/imports", "Imports", "Link .cra files through an explicit import graph.", "language", 20, ["docs/language/language-foundation.md", "examples/imports/runPosts.cra"], `# Imports\n\nUse the supported file import syntax. The C++ project linker resolves a deterministic import graph before semantic analysis.\n\n\`\`\`cra\nimport #postsRepository.cra#\n\nprint(getPosts())\n\`\`\`\n\nKotlin and Swift do not parse imports or reimplement Crossa semantics.`),
  doc("/docs/language/types", "Types", "Supported V0 scalar and collection types.", "language", 30, ["docs/language/language-foundation.md"], `# Types\n\nThe current foundation includes \`Int\`, \`Long\`, \`Double\`, \`String\`, \`Bool\`, models, and \`List<T>\`. \`List<T>\` is a built-in typed collection rather than a general user-defined generic system.\n\nFor large results, platform bindings can expose native-backed views where the generated API supports them.`),
  doc("/docs/language/variables", "Variables", "Use explicit typed variables in .cra source.", "language", 40, ["docs/language/language-foundation.md"], `# Variables\n\nVariables use \`var\` and explicit types. The semantic analyzer resolves symbols and types before runtime execution.\n\n\`\`\`cra\nvar name: String = "ahmad"\nprint("Name is: #name")\n\`\`\``),
  doc("/docs/language/functions", "Functions", "Define typed operations with fun and re.", "language", 50, ["docs/language/language-foundation.md"], `# Functions\n\nA function declares typed parameters and a result type. Use \`re\` to return an expression.\n\n\`\`\`cra\nfun add(a: Int, b: Int): Int {\n    re a + b\n}\n\`\`\`\n\nPure translated IR can be generated as Kotlin or Swift. Runtime-backed operations use thin native wrappers.`),
  doc("/docs/language/control-flow", "Control flow", "Use the supported if / else language control flow.", "language", 60, ["docs/language/language-foundation.md", "docs/decisions/0005-conditional-control-flow.md"], `# Control flow\n\nThe foundational language supports \`if\`, \`else if\`, and \`else\`. Conditions are validated through semantic analysis; generators consume typed meaning rather than reparsing source text.`),
  doc("/docs/language/models", "Models", "Declare strongly typed Crossa model identities.", "language", 70, ["docs/language/language-foundation.md", "examples/imports/domain/models.cra"], `# Models\n\nModels define typed fields used by request decoding and generated platform surfaces. Public model files should normally use one model per file and match the filename stem.\n\n\`\`\`cra\nmodel Post(\n    userId: Int,\n    id: Int,\n    title: String,\n    body: String\n)\n\`\`\``),
  doc("/docs/language/interpolation", "Interpolation", "Compile #identifier segments into typed string plans.", "language", 80, ["docs/language/language-foundation.md"], `# Interpolation\n\nCrossa supports \`#identifier\` interpolation. The compiler resolves the interpolation before execution, avoiding a second scan of raw source strings at runtime.\n\n\`\`\`cra\npath: "/v1/users/#id"\n\`\`\``),
  doc("/docs/language/async", "Async execution", "Choose Sync, Async, or AsyncAfter execution policy.", "language", 90, ["docs/language/language-foundation.md", "ARCHITECTURE.md"], `# Async execution\n\n\`@Async\` and \`@AsyncAfter\` use the shared bounded Crossa scheduler, not one OS thread per invocation. \`@AsyncAfter\` delivers exactly one terminal result: \`Success(data)\`, \`Failed(error)\`, or \`Cancelled\`.\n\nPlatform bindings bridge completion and cancellation; they do not execute the function body again.`),
  doc("/docs/language/configuration", "Configuration", "Use config.cra for project and runtime defaults.", "language", 100, ["docs/language/language-foundation.md", "docs/platform/android.md"], `# Configuration\n\n\`config.cra\` is a reserved declarative source file for project/runtime configuration. It is compiled into the generated native program and never becomes a normal Kotlin or Swift API class. Do not place secrets in generated artifacts or build-variant literals.`),
  doc("/docs/language/crossa-request", "CrossaRequest", "Describe native HTTP execution with a typed request expression.", "language", 110, ["docs/language/language-foundation.md", "docs/features/networking.md"], `# CrossaRequest\n\n\`CrossaRequest\` is a compiler/runtime builtin. It lowers through semantic validation into a typed native request plan. It does not generate independent Retrofit, Ktor, Alamofire, or URLSession clients.\n\n${code}`),
  doc("/docs/runtime", "Runtime", "Native execution, scheduling, ownership, and networking.", "runtime", 0, ["ARCHITECTURE.md"], `# Native runtime\n\nC++ owns performance-critical request planning, transport, response buffering, decoding, model storage, scheduling, async state, errors, cancellation, and memory. Kotlin and Swift expose ergonomic views over this path.`),
  doc("/docs/runtime/architecture", "Runtime architecture", "How source becomes a native request plan and platform result.", "runtime", 10, ["ARCHITECTURE.md", "docs/features/networking.md"], `# Runtime architecture\n\n\`.cra\` source moves through loader, lexer, parser, linked AST, semantic analysis, typed IR, and native request generation. The runtime executes HTTP and JSON decoding, then provides typed native results through the stable ABI.`),
  doc("/docs/runtime/scheduler", "Bounded scheduler", "Asynchronous work is coordinated by the shared native scheduler.", "runtime", 20, ["docs/runtime/scheduling.md", "ARCHITECTURE.md"], `# Bounded scheduler\n\nCrossa owns its scheduling resources per runtime. Async operations use the shared bounded scheduler; a request does not create an unconstrained OS thread. Shutdown, cancellation, and callback delivery are explicit lifecycle concerns.`),
  doc("/docs/runtime/ownership", "Ownership", "Native result lifetime and platform views.", "runtime", 30, ["docs/runtime/memory-ownership.md", "docs/platform/android.md", "docs/platform/ios.md"], `# Ownership\n\nThe native runtime owns result and error storage. Model and list values can be borrowed native-backed views with an owning result lifetime; scalar results can be copied and released. Bindings must close or release views before runtime teardown.`),
  doc("/docs/runtime/networking", "Networking", "Native HTTP planning, transport, decoding, cancellation, and errors.", "runtime", 40, ["docs/features/networking.md", "ARCHITECTURE.md"], `# Networking\n\nCrossa validates and plans requests, constructs URL/path/query/header/body data, performs transport, buffers responses, decodes typed results, and owns errors, retries, cleanup, and cancellation in native code. Platform code is not a second networking runtime.`),
  doc("/docs/android", "Android", "Generate a native-backed Android Gradle library and AAR.", "platform", 0, ["docs/platform/android.md"], `# Android\n\n\`crossa generate-build android\` compiles a linked project and writes an Android Gradle library. It embeds the native runtime and produces Debug/Release AAR variants for the supported \`arm64-v8a\` path.`),
  doc("/docs/android/getting-started", "Android getting started", "Generate an Android project and assemble its AAR.", "platform", 10, ["docs/platform/android.md", "android-example/README.md"], `# Android getting started\n\n\`\`\`bash\ncrossa generate-build android ./crossa-project --output ./build/crossa-aar\n\`\`\`\n\nThe generated project carries a Gradle Wrapper and native CMake configuration. The Android example consumes a generated Release AAR; its benchmark artifact is not a universal SDK.`),
  doc("/docs/android/generated-api", "Generated Android API", "Thin Kotlin APIs over the native runtime and JNI bridge.", "platform", 20, ["docs/platform/android.md", "android-example/app/src/main/java/com/crossa/androiddemo/network/CrossaPostsClient.kt"], `# Generated Android API\n\nGenerated Kotlin functions expose cancellable callbacks and suspend operations. \`CrossaState.Success\`, \`CrossaState.Failed\`, and \`CrossaState.Cancelled\` represent terminal state. Kotlin forwards to a small registered JNI bridge; native C++ owns request execution and result storage.`),
  doc("/docs/android/native-models", "Native Android models", "Native-backed model and list views at the Kotlin boundary.", "platform", 30, ["docs/platform/android.md"], `# Native Android models\n\nGenerated models, \`CrossaNativeList\`, and JSON values are borrowed views over a native result. Nested model/list fields can remain native-backed. Closing a result prevents later access through the Kotlin boundary.`),
  doc("/docs/android/aar", "AAR generation", "Build and package the generated Android library.", "platform", 40, ["docs/platform/android.md"], `# AAR generation\n\nThe command writes a self-contained Android Gradle library project. It declares Debug and Release configurations; the generated project is the input for Gradle AAR assembly. \`crossa doctor\` reports Android build prerequisites without changing machine configuration.`),
  doc("/docs/ios", "iOS", "Generate the project-specific Crossa XCFramework.", "platform", 50, ["docs/platform/ios.md"], `# iOS\n\n\`crossa generate-build ios\` emits an Xcode framework project and archives Debug and Release device/simulator variants into XCFrameworks. Swift does not parse \`.cra\`, perform HTTP, decode responses, or schedule native work.`),
  doc("/docs/ios/getting-started", "iOS getting started", "Build an XCFramework and integrate it into an app.", "platform", 60, ["docs/platform/ios.md", "ios-example/README.md"], `# iOS getting started\n\n\`\`\`bash\ncrossa generate-build ios ./crossa-project --output ./build/crossa-ios\n\`\`\`\n\nThe command creates Debug and Release XCFramework outputs. The generated framework is project-specific. Use the Release artifact for consumer examples and benchmark observation.`),
  doc("/docs/ios/generated-api", "Generated iOS API", "Swift runtime, operation, and terminal result integration.", "platform", 70, ["docs/platform/ios.md", "ios-example/CrossaIOSExample/Networking/Crossa/CrossaPostsRepository.swift"], `# Generated iOS API\n\nThe public Swift module is \`Crossa\`. \`CrossaRuntime\` owns a native runtime handle and \`CrossaOperation\` bridges cancellation. \`@AsyncAfter\` exposes \`.success\`, \`.failed(CrossaError)\`, and \`.cancelled\`; callbacks are not implicitly dispatched to the main thread.`),
  doc("/docs/ios/native-models", "Native iOS models", "Lazy model and list access through stable ABI value paths.", "platform", 80, ["docs/platform/ios.md"], `# Native iOS models\n\nGenerated model and \`CrossaList\` values retain an internal native result owner. Field and list access use schema indexes and stable ABI value paths. Scalar terminal values are copied and their native result can be released immediately.`),
  doc("/docs/ios/xcframework", "XCFramework generation", "Debug/Release frameworks and package metadata.", "platform", 90, ["docs/platform/ios.md"], `# XCFramework generation\n\nThe build archives device and simulator variants with \`xcodebuild archive\`, then creates an XCFramework. Release output includes an archive ZIP, checksum, Package.swift, dSYMs, and artifact metadata. It is not a universal runtime artifact.`),
  doc("/docs/cli", "CLI", "Crossa commands, interactive mode, and environment inspection.", "cli", 0, ["docs/development/cli.md"], `# Crossa CLI\n\nRunning \`crossa\` with no arguments opens an interactive wizard when stdin is a terminal. Explicit commands remain non-interactive and \`--no-input\` makes that policy explicit.\n\n\`run\`, \`check\`, \`test\`, \`generate kotlin\`, \`generate-build android\`, \`generate-build ios\`, \`doctor\`, and \`--version\` are currently documented commands.`),
  doc("/docs/cli/commands", "CLI commands", "Use explicit commands for validation, execution, and generation.", "cli", 10, ["docs/development/cli.md"], `# CLI commands\n\n\`\`\`bash\ncrossa check file.cra\ncrossa run file.cra\ncrossa test file.cra\ncrossa generate kotlin file.cra --output ./generated\ncrossa generate-build android ./project --output ./build/android\ncrossa generate-build ios ./project --output ./build/ios\n\`\`\`\n\nUse \`--debug\` where supported to show compiler and IR details during execution.`),
  doc("/docs/cli/doctor", "Doctor", "Check Crossa, Android, iOS, and storage prerequisites.", "cli", 20, ["docs/development/cli.md", "docs/platform/android.md"], `# Doctor\n\n\`crossa doctor\` inspects Crossa installation, host details, Android and iOS prerequisites, and writable storage. It does not install dependencies, alter environment variables, or edit shell configuration.\n\nRows use passed, warning, and failed symbols. Required failures return non-zero and include a Fix section.`),
  doc("/docs/cli/generate-build", "Generate build", "Create project-specific Android and iOS native artifacts.", "cli", 30, ["docs/development/cli.md", "docs/platform/android.md", "docs/platform/ios.md"], `# Generate build\n\nAndroid generation accepts an optional entry and tool version overrides for one generated project. iOS generation can set package version and base URL for binary-target package metadata. Both commands preserve the source commit and CLI identity in artifact metadata.`),
  doc("/docs/architecture", "Architecture", "The compiler, typed IR, native runtime, ABI, and platform outputs.", "reference", 10, ["ARCHITECTURE.md"], `# Crossa architecture\n\n\`\`.cra source → C++ loader/lexer/parser → linked semantic model → typed IR → generated native program → C++ runtime → stable ABI → Android AAR / iOS XCFramework\`\`\n\nThe compiler frontend, networking, scheduler, decoding, typed model storage, and memory ownership remain in C++. Kotlin and Swift expose platform-facing APIs over that shared semantic path.`),
  doc("/docs/benchmarks", "Benchmark evidence", "How to interpret retained development benchmark snapshots.", "reference", 20, ["android-example/README.md", "ios-example/README.md"], `# Benchmark evidence\n\nThe checked-in snapshots are development observations from a Release artifact, remote JSONPlaceholder endpoint, and emulator/simulator environments. Warmups are excluded; samples rotate implementation order.\n\n> These results are not physical-device performance guarantees and should not be treated as SDK-only measurements.\n\nThe benchmark explorer shows raw observed p50/p95 summaries and their artifact metadata.`),
  doc("/docs/troubleshooting", "Troubleshooting", "Start with exact diagnostics and generation manifests.", "reference", 30, ["docs/development/cli.md", "docs/platform/android.md", "docs/platform/ios.md"], `# Troubleshooting\n\nRun \`crossa doctor\` first. For generation, retain the command output and generated artifact manifest: it records CLI path, SHA-256, Crossa source commit, runtime ABI, target, and build configuration.\n\nCheck that the CLI and generated consumer artifact originate from compatible source commits before treating an integration result as release evidence.`)
] as const satisfies readonly DocumentationDefinition[];

export function getDocument(pathname: string): DocumentationDefinition | undefined {
  const normalized = pathname.replace(/\/$/, "") || "/docs";
  return documentationCatalog.find((entry) => entry.slug === normalized);
}

export function documentsInSection(section: DocumentationSection): readonly DocumentationDefinition[] {
  return documentationCatalog.filter((entry) => entry.section === section).sort((a, b) => a.order - b.order);
}
